server {
    listen 5.188.24.69:80;
    server_name 5.188.24.69;
    root /var/www/soulark;
    index index.html;
    gzip on;
    gzip_types text/html text/css application/javascript image/png image/jpeg font/woff;
    location / {
        try_files $uri $uri/ =404;
    }
}
